on: [push, workflow_dispatch]

name: release

jobs:

  kbld-publish:
    name: Release ko artifact
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write  # undocumented OIDC support.
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: setup ko
        run: go install github.com/google/ko@main
      - uses: sigstore/cosign-installer@main
      - name: login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $(echo ${{ github.actor }} | awk '{print tolower($0)}') --password-stdin
      - name: install carvel
        run: curl -L https://carvel.dev/install.sh | bash
      - name: build and sign image
        run: |
          set -e -x
          export COSIGN_EXPERIMENTAL=1
          kbld -f kbuild.yml | yq eval '.image' - | xargs -n1 cosign sign -a git_sha=$GITHUB_SHA